# Site Settings
title: "My Portfolio"
name: "Thomas"
description: "Personal portfolio and project showcase"
url: "https://thomas12358.github.io"
baseurl: ""

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Site Author
author:
  name: "Thomas Charlton"
  bio: "A chemical engineer that likes to code."
  location: "Vancouver, Canada"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/thomas-charlton-74234565/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Thomas12358"

# Reading Files
include:
  - _pages

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Navigation
header:
  overlay_color: "#000"
  overlay_filter: "0.5"

navigation_links: main
